### ISSUE TITLE
How start radar on linux?

### ISSUE THREAD

**Issue by Lafko** [Jerry1211/RadarProject#15]
How to start the radar on the same computer as Windows?

```
root@DESKTOP-xxxxx:/home# java -jar RADAR.jar 192.168.100.2 PortFilter 192.168.100.2
6
6
7
Exception in thread "main" org.pcap4j.core.PcapNativeException: eth0: socket: Invalid argument
        at org.pcap4j.core.PcapNetworkInterface.openLive(PcapNetworkInterface.java:283)
        at main.sniffer.Sniffer$Companion.sniffLocationOnline(Sniffer.kt:126)
        at main.GameKt.main(Game.kt:57)
```

Using:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

net.ipv4.ip_forward = 1

**Comment by Lafko** [comment]
So please remove the sound from the code.
```
 private var lastPlayTime = System.currentTimeMillis()
    private fun safeZoneHint() {
        if (PoisonGasWarningPosition.len() > 0) {
            val dir = PoisonGasWarningPosition.cpy().sub(selfCoords)
            val road = dir.len() - PoisonGasWarningRadius
            if (road > 0) {
                val runningTime = (road / runSpeed).toInt()
                val (x, y) = dir.nor().scl(road).add(selfCoords).mapToWindow()
                littleFont.draw(spriteBatch, "$runningTime", x, windowHeight - y)
                val remainingTime = (TotalWarningDuration - ElapsedWarningDuration).toInt()
                if (remainingTime == 60 && runningTime > remainingTime) {
                    val currentTime = System.currentTimeMillis()
                    if (currentTime - lastPlayTime > 10000) {
                        lastPlayTime = currentTime
                        alarmSound.play()
```
Alarm.wav
