### ISSUE TITLE
last update had some issues with compiling.

### ISSUE THREAD

**Issue by Dragonflyss** [Jerry1211/RadarProject#40]
the last update has some error after building. The radar is opening at first, but wen you start pubg its says:
72 lost the first actor creation bunch. just create as we need it.
37 lost the first actor creation bunch. just create as we need it.
Exception in thread "Thread-1" java.lang.IndexOutOfBoundsException
        at pubgradar.deserializer.Buffer.readBit(Buffer.kt:89)
        at pubgradar.deserializer.Buffer.readInt(Buffer.kt:126)
        at pubgradar.deserializer.PacketParserKt.proc_raw_packet(PacketParser.kt:83)
        at pubgradar.deserializer.PacketParserKt.proc_raw_packet(PacketParser.kt:52)
        at pubgradar.deserializer.PacketParserKt$parsePackets$1.invoke(PacketParser.kt:34)
        at pubgradar.deserializer.PacketParserKt$parsePackets$1.invoke(PacketParser.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18).

didnt had the problem before

**Comment by wuwujia** [comment]
me too infact...

**Comment by MadCabalo** [comment]
Same happened to me. I assumed it was a server side issue.

**Comment by Dragonflyss** [comment]
I know what to do! You have to open radar wen you are in the main menu of pubg. Not before launch like before

**Comment by 470434839** [comment]
first open game，then open radar

**Comment by the7thway** [comment]
what? open game first then radar??????
